### ISSUE TITLE
Switch to src-layout

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/pymmcore#108]
As defined [here](https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/), i.e., just move `pymmcore/` to `src/pymmcore/`.

With the current layout, care needs to be taken when locally testing the build because Python can pick up files in `pymmcore/` as part of the `pymmcore` package.

**Comment by tlambert03** [comment]
I’m all for it.
