### ISSUE TITLE
Unable to connect NikonTi microscope (Windows fatal exception: access violation)

### ISSUE THREAD

**Issue by hmanko** [micro-manager/pymmcore#116]
I was using pymmcore to control NikonTi microscope and two cameras. We recently received a new computer with Windows 11 on which I am trying to do the same. Everything **works well through Micromanager** and two cameras can be controlled using python script.  However, when trying to connect NikonTi via pymmcore I am receiving an error when loading system configuration
`mmc.loadSystemConfiguration(os.path.join(path, config))`:

```
Windows fatal exception: access violation

Main thread:
Thread 0x000016e4 (most recent call first):
  File "C:\Users\User\AppData\Local\Temp\ipykernel_9424\1486552245.py", line 1 in <module>

Restarting kernel... 
```
(The folder 'ipykernel_9424' does not exist, if I am trying to create it, the number (\*_9424) changes)(??)

The event application error on Windows in this case is:

```
Faulting application name: python.exe, version: 3.9.18150.1013, time stamp: 0x64ff232c
Faulting module name: OLEAUT32.dll, version: 10.0.22621.2506, time stamp: 0x6649ab4c
Exception code: 0xc0000005
Fault offset: 0x000000000000d6f3
Faulting process id: 0x0x20D4
Faulting application start time: 0x0x1DA76E54BE65E12
Faulting application path: C:\Users\User\miniconda3\envs\my_env\python.exe
Faulting module path: C:\Windows\System32\OLEAUT32.dll
Report Id: 90792ce8-3422-4ebb-b350-166a2ef5f09b
Faulting package full name: 
Faulting package-relative application ID: 
```

The code:
```
import pymmcore
import os.path

path = 'C:\Program Files\Micro-Manager-2.0'
config = 'NikonTi.cfg' 

mmc.pymmcore.CMMCore()
mmc.setDeviceAdapterSearchPath([path])
mmc.loadSystemConfiguration(os.path.join(path, config))
```
Everything was installed for 64 bit system. The Micromanager folder was set as a working directory. The same behavior was observed in Spyder, PyCharm and in command prompt(but error is not displayed). I tried different environments with python3.8, 3.9, 3.11. The same result was obtained with Micromanager 2.0 and last Nightly Builds version, by using corresponding versions of pymmcore.

**Comment by tlambert03** [comment]
one thing to check, similar to https://github.com/micro-manager/pymmcore/issues/28, is that the device adapter search path is also in your environment PATH.  See the additional logic [added here](https://github.com/pymmcore-plus/pymmcore-plus/blob/main/src/pymmcore_plus/core/_mmcore_plus.py#L301-L305) in pymmcore-plus when calling `mmc.setDeviceAdapterSearchPath`:

```python
        env_path = os.environ["PATH"]
        for p in paths:
            if p not in env_path:
                env_path = p + os.pathsep + env_path
        os.environ["PATH"] = env_path
```

**Comment by hmanko** [comment]
The adding Micromanager folder to environmental PATH did not help. I still encounter the same error.

**Comment by hmanko** [comment]
> one thing to check, similar to #28, and [described in the readme](https://github.com/micro-manager/pymmcore?tab=readme-ov-file#loading-device-adapters-on-windows), is that the device adapter search path is also in your environment PATH. See the additional logic [added here](https://github.com/pymmcore-plus/pymmcore-plus/blob/main/src/pymmcore_plus/core/_mmcore_plus.py#L301-L305) in pymmcore-plus when calling `mmc.setDeviceAdapterSearchPath`:
> 
> ```python
>         env_path = os.environ["PATH"]
>         for p in paths:
>             if p not in env_path:
>                 env_path = p + os.pathsep + env_path
>         os.environ["PATH"] = env_path
> ```

The adding Micromanager folder to environmental PATH did not help. I still encounter the same error.

**Comment by tlambert03** [comment]
can you elaborate a bit on exactly how you created your environment, and how you're running this script?  the presence of `ipykernel_9424` is interesting.  You did mention "The same behavior was observed in Spyder, PyCharm and in command prompt(but error is not displayed)" ... but just want to check you've specifically tried to do this without involving jupyter, etc...

And, since the final issue appears to be related to ipykernel.  Let's try to simplify this and see if it's just an environment problem.  have you determined that this is or isn't actually related to the Ti itself?  Can you, for example, load the demo camera ok?

```python
import pymmcore

mmc = pymmcore.CMMCore()
mmc.setDeviceAdapterSearchPath(['C:\Program Files\Micro-Manager-2.0'])
mmc.loadDevice('Camera', 'DemoCamera', 'DCam')
mmc.initializeDevice('Camera')
```

**Comment by hmanko** [comment]
The two cameras (AndorSDK3 and PICAM device adapters) are working correctly. 

The environment was created using conda with specified python version. Currently I am using Spyder to run the script (the spyder was installed using conda, inside the environment). 
Yes, there is a difference depending on how exactly I run the script. I was doing it by running the selected lines (or line by line), if I run the full file the error is a bit different:
```
Windows fatal exception: access violation


Main thread:
Thread 0x000027e4 (most recent call first):
  File "D:\Codes\code\testScript.py", line 17 in <module>
  File "C:\Users\User\miniconda3\envs\MyEnv\lib\site-packages\spyder_kernels\py3compat.py", line 356 in compat_exec
  File "C:\Users\User\miniconda3\envs\MyEnv\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 473 in exec_code
  File "C:\Users\User\miniconda3\envs\MyEnv\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 615 in _exec_file
  File "C:\Users\User\miniconda3\envs\MyEnv\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 528 in runfile
  File "C:\Users\User\AppData\Local\Temp\ipykernel_12668\947401585.py", line 1 in <module>


Restarting kernel...
```

Previously I used PyCharm by accessing the created environment or by creating new PyCharm project environment. 
I just checked again, actually in PyCharm the error is just `Process finished with exit code -1073741819 (0xC0000005)`. Also in event application there is second error just after previously reported one:
```
Faulting application name: NikonTiS.exe, version: 4.4.1.714, time stamp: 0x51b99d04
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0000000000000000
Faulting process id: 0x0x2F00
Faulting application start time: 0x0x1DA794908E4C0A2
Faulting application path: C:\Program Files\Nikon\Shared\Bin\NikonTiS.exe
Faulting module path: unknown
Report Id: f496d547-fbdf-4383-8675-6fdc53b22c4a
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by hmanko** [comment]
Hello @tlambert03 and thank you for your help !
I have identified the problem; there was an issue with the Nikon software installation on the new computer (the second application event error was saying about faulty applications: NikonTiS.exe). Simply copying and pasting the folder 'C:\Program Files\Nikon' from the old machine and replacing the files resolved the issue.

**Comment by tlambert03** [comment]
Awesome 👍 thanks for the update!
