### ISSUE TITLE
Error messages obscured

### ISSUE THREAD

**Issue by campagnola** [micro-manager/pymmcore#15]
I've generated errors a few different times using pymmcore and so far the last line of the tracebacks all look like this:

    RuntimeError: <Swig Object of type 'CMMError *' at 0x00000210CFAE1870>

It would be helpful to unpack the actual error message here.

**Comment by tlambert03** [comment]
+1

spent some time trying to work on this yesterday. It appears that the [attempt to extend `CMMError`](https://github.com/micro-manager/micro-manager/blob/1bfca365a6fe3873cc3977271a72dd2a7e63855a/MMCorePy_wrap/MMCorePy.i#L223-L234) with a `__str__` method isn't working:

```python
In [1]: import pymmcore

In [2]: mmc = pymmcore.CMMCore()

In [3]: mmc.loadSystemConfiguration("nonsense")
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-d2aa6ccbfc0b> in <module>
----> 1 mmc.loadSystemConfiguration("nonsense")

RuntimeError: <Swig Object of type 'CMMError *' at 0x7faca06ca470>

In [4]: import sys

In [5]: exc = sys.last_value

In [6]: cmmerror = exc.args[0]

# if __str__ was working this should work right?
In [7]: print(cmmerror)
<Swig Object of type 'CMMError *' at 0x7faca06ca470>

In [8]: cmmerror.getFullMsg()
Out[8]: '"nonsense": File open failed.'
```

I also tried using the SWIG [`%exception` directive](http://www.swig.org/Doc3.0/Customization.html#Customization_exception) to modify the `PyExc_RuntimeError` directly, but couldn't get that to work either.  @marktsuchida, if you have tips on possible next steps here, I'm happy to keep digging.

**Comment by marktsuchida** [comment]
@tlambert03 Thanks for investigating. I'm afraid I don't have any ideas off the top of my head, other than to read the SWIG docs. Did you also try the `%exception` directive together with the `SWIG_exception(SWIG_RuntimeError, "message");` call?

**Comment by tlambert03** [comment]
I didn't try that yet... but I will, thanks!  I had only tried that example at the top... something like the try catch followed by `PyErr_SetString` and `SWIG_fail;`.  I'll let you know what I find.

**Comment by tlambert03** [comment]
figured it out!  The `throw (CMMError)` exception specification used in most signatures turned out to be part of the problem, and makes the `%exception` directive not work here.  the ["throws" typemap](http://www.swig.org/Doc1.3/Typemaps.html#throws_typemap) turned out to be the answer.  Fix submitted here: https://github.com/micro-manager/micro-manager/pull/1157

**Comment by marktsuchida** [comment]
Great! Yeah, the `throw (MyClass)` syntax is no longer allowed in C++17, so we will eventually need an alternative way, but that's another topic entirely. (MMCoreJ also currently uses `%exception(throws, ...)`.)

**Comment by tlambert03** [comment]
> MMCoreJ also currently uses %exception(throws, ...)

noticed that only afterwards unfortunately! 😅

**Comment by tlambert03** [comment]
with https://github.com/micro-manager/mmCoreAndDevices/pull/9 merged, we should be able to close this issue... but we'll need a new pymmcore release correct?

**Comment by marktsuchida** [comment]
Yes, I'll create a release soon -- hopefully tomorrow.
