### ISSUE TITLE
error load Hamamtsu Camera

### ISSUE THREAD

**Issue by KawashimaLab** [micro-manager/pymmcore#21]
Hi,

I am getting the following error while trying to load the Hamamatsu Camera by this command:
mmc.loadDevice('Camera','HamamatsuHam', 'HamamatsuHam_DCAM')

or by this command:
mmc.loadSystemConfiguration(os.path.join(mm_dir, "MMConfig_hamamatsu.cfg"))

with the error thrown being the following (which is not very informative to me):
RuntimeError: <Swig Object of type 'CMMError *' at 0x0000014BCB37AEA0>

I moved to pymmcore in order to work under python3

I didn't have any problem with loading the camera while working under python2 and the MMCorePy

any suggestion on this?

Thank you
Rani

**Comment by marktsuchida** [comment]
Can you see what happens if you try to load the Demo config shipped with Micro-Manager? This will reveal whether it is an issue with your configuration or something specific to Hamamatsu.

**Comment by felix92** [comment]
Hi all,
I think it is not possible to use the Hamamatsu camera with python3 but only with python2.

Best,
Felix
