### ISSUE TITLE
Import Error on numpy.core.multiarray

### ISSUE THREAD

**Issue by ninjamelons** [micro-manager/pymmcore#24]
importing pymmcore gives an import error in pymmcore.py saying it fails to import numpy.core.multiarray.

`Traceback (most recent call last):
  File "pymmWrap.py", line 1, in <module>
    import pymmcore
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "pymmcore.py", line 15, in <module>
ImportError: numpy.core.multiarray failed to import`

After a while of searching I found that i can fix it by importing numpy in my python file before importing pymmcore but this seems like an error in pymmcore.

**Comment by nicost** [comment]
I think this is address in Talley Lambert's PR #23.  I just Merged that Pull Request.  Not sure if this is automatically build or that I need to do something to trigger a build.  @marktsuchida, hope that you can trigger a build.

**Comment by marktsuchida** [comment]
I'm not sure how this relates to #23, which is about building, not importing, pymmcore.

I'm not seeing this symptom in at least one environment I tested, so can you provide your OS, Python, NumPy, and pymmcore versions?

**Comment by ninjamelons** [comment]
Fixed itself after I believe a system restart. Can't re-create it anymore.
