### ISSUE TITLE
DeviceAdapter (TIScam) that works in micro-manager, not working in pymmcore

### ISSUE THREAD

**Issue by tlambert03** [micro-manager/pymmcore#28]
I'm looking for some tips in debugging an issue wherein a device adapter that works fine in micro-manager proper, fails to load (with missing dependency) in pymmcore:

pymmcore is generally working and the demo config works fine:
```python
In [1]: import pymmcore

In [2]: mmc = pymmcore.CMMCore()

In [3]: mmc.setDeviceAdapterSearchPaths(('C:\\Program Files\\Micro-Manager-2.0gamma',))

In [4]: mmc.loadSystemConfiguration('C:\\Program Files\\Micro-Manager-2.0gamma\\MMConfig_demo.cfg')

In [5]: mmc.getCameraDevice()
Out[5]: 'Camera'
```

I have a minimal test config with a single TIScam that works fine in the main micro-manager gui (loads and snaps an image)

```ini
# c:\\Users\\talley\\Desktop\\test.cfg

# Reset
Property,Core,Initialize,0
# Devices
Device,Camera,TIScam,TIS_DCAM
# Initialize
Property,Core,Initialize,1
# Roles
Property,Core,Camera,Camera
Property,Core,AutoShutter,1
```

However, when I attempt to load that same config with pymmcore, I get a missing module error:

```python
In [6]: try:
    ...:     mmc.loadSystemConfiguration('c:\\Users\\talley\\Desktop\\test.cfg')
    ...: except Exception as e:
    ...:     print(e.args[0].getFullMsg())
    ...: 
Line 4: Device,Camera,TIScam,TIS_DCAM
Failed to load device "TIS_DCAM" from adapter module "TIScam" 
[ Failed to load device adapter "TIScam" 
	[ Failed to load module "C:\Program Files\Micro-Manager-2.0gamma\mmgr_dal_TIScam.dll" 
		[ The module, or a module it depends upon, could not be found (Windows error: The specified module could not be found.) ] ] ]

In [7]: import os

# but the module itself definitely exists
In [8]: os.path.exists('C:\Program Files\Micro-Manager-2.0gamma\mmgr_dal_TIScam.dll')
Out[8]: True
```

I'm wondering whether there is some additional library search paths that might be added when running the actual micro-manager GUI that are missing when running via pymmcore?  I tried digging a bit with dependency walker, but a _lot_ was missing there. (if there is a section in the micro-manager source code or in the device adapter code that I should be looking through, I'm happy to dig there with some guidance!)

I'm running Win10, py3.8.6, with MM-2.0.0-gamma1-20201220

thank you!
cc @nicost

**Comment by nicost** [comment]
It seems that mmgr_dal_TIScam.dll itself is found (otherwise, mmgr_dal_DemoCamera.dll would not have been found either), but something it depends on is not found.  The VS build file for TIScam does not list .lib files it is linked against, which makes me believe that code is looking to load libraries dynamically.  I remember issues like this when people were running Micro-Manager from within matlab, and it always came down to setting the $PATH variable.  In matlab is was essential to add the Micro-Manager directory to the path.  Can you check what the $PATH variable is in your environment, and is it possible to add the Micro-Manager directory (at least to try, it is possible that a path to the TIScam code needs to be added as well).

**Comment by tlambert03** [comment]
thank you @nicost!  adding the Micro-Manager directory to PATH did it!  If I may trouble you with two more questions (just for my own education 😊):

- when you checked the VS build file for TIScam for library links, do you mean `TISCam/TIScam.vcxproj` or `TISCam/build.xml`?  can you point me to an adapter that does state an explicit linkage in the build file?

- what is it about launching micro-manager directly that allowed TISCam to find whatever it needed?  Is it the second item in the "standard search order" [mentioned here](https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#standard-search-order-for-uwp-apps) (i.e. "the system searches ... the directory the calling process was loaded from")?

**Comment by nicost** [comment]
> when you checked the VS build file for TIScam for library links, do you mean TISCam/TIScam.vcxproj or TISCam/build.xml? can you point me to an adapter that does state an explicit linkage in the build file?

TISCam/TIScam.vcxproj.  An example of an adapter that has explicit dependencies is AndorSDK3 (look in project properties under Linker-General and Linker-Input.  

> what is it about launching micro-manager directly that allowed TISCam to find whatever it needed? Is it the second item in the "standard search order" mentioned here (i.e. "the system searches ... the directory the calling process was loaded from")?

Yes, pretty sure that is it.  

B.t.w., I note two TIS_*.dll in the Micro-Manager installation directory.  I forgot how those are included in the installer, but likely the files that the TIScam adapter is looking for.

**Comment by tlambert03** [comment]
thanks again for your time!

**Comment by marktsuchida** [comment]
For future reference, this is an instance of what is described under "Loading device adapters on Windows" in the README file.

**Comment by tlambert03** [comment]
oh man 🤦‍♂️ ... sorry :)  thanks again!
