### ISSUE TITLE
loading NikonTi2 dll

### ISSUE THREAD

**Issue by yellenlab** [micro-manager/pymmcore#42]
I am trying to load a configuration based on the Ti2_Mic_Driver.dll, as discussed on the micromanager wiki.  It works fine when I load the config file in the micromanager gui, however when I do it through pymmcore, I get an error.  

I am using the following code:

import pymmcore
import os.path
mm_dir = "C:/Program Files/Micro-Manager-2.0gamma"
mmc = pymmcore.CMMCore()
mmc.setDeviceAdapterSearchPaths([mm_dir])
mmc.loadSystemConfiguration(os.path.join(mm_dir, "custom.cfg"))

and I get this error message:

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-3-71df56c56838> in <module>
----> 1 mmc.loadSystemConfiguration(os.path.join(mm_dir, "custom.cfg"))
      2 
      3 mmc.snapImage()
      4 mmc.getImage()

OSError: Line 7: Device,Ti2-E__0,NikonTi2,Ti2-E__0
Failed to load device "Ti2-E__0" from adapter module "NikonTi2" [ Failed to load device adapter "NikonTi2" [ Failed to load module "C:/Program Files/Micro-Manager-2.0gamma\mmgr_dal_NikonTi2.dll" [ The module, or a module it depends upon, could not be found (Windows error: The specified module could not be found.) ] ] ]

It is calling the mmgr_dal_NikonTi2.dll file rather than the Ti2_Mic_Driver.dll.

**Comment by marktsuchida** [comment]
Most likely it needs help finding the Nikon-provided DLLs (which you probably copied into Micro-Manager so that the GUI works). The error message you quoted is identical whether it is mmgr_dal_NikonTi2.dll or one of its transient dependencies that is missing.

Can you try the methods described [here](https://github.com/micro-manager/pymmcore#loading-device-adapters-on-windows)?

**Comment by yellenlab** [comment]
Thanks for the suggestion.  As it turns out, the os.chdir() method works but setting the path to micromanager didn't.  Since the os.chdir() worked, I didn't investigate beyond a quick attempt.
