### ISSUE TITLE
accept type stubs?

### ISSUE THREAD

**Issue by tlambert03** [micro-manager/pymmcore#43]
I have written type stubs for pymmcore that I find extremely handy.  For example, with stubs present in the environment, VScode (and other IDEs) can provide autocompletion, linting, and type validation with mypy:

<img width="568" alt="Untitled 2" src="https://user-images.githubusercontent.com/1609449/125117995-0e66f000-e0bd-11eb-994d-7ae9ec57be76.png">
<img width="545" alt="Untitled" src="https://user-images.githubusercontent.com/1609449/125117996-0e66f000-e0bd-11eb-9698-8bbf994dabf2.png">

would you want/be willing to distribute the `pyi` file in along with this package (see [PEP 561](https://www.python.org/dev/peps/pep-0561/#packaging-type-information))?   The one thing I haven't done before is provide type stubs for a single-module package like pymmcore ... but we could figure that out I'm sure.

The alternatives are for me to submit to [typeshed](https://github.com/python/typeshed), or to distribute a [stub-only package](https://www.python.org/dev/peps/pep-0561/#stub-only-packages).

**Comment by marktsuchida** [comment]
Would love to include this!

If it is easier, I could change pymmcore to be a proper package, instead of a single module. It's probably a good idea anyway.

**Comment by tlambert03** [comment]
> If it is easier, I could change pymmcore to be a proper package, instead of a single module.

That would be great if you have no objections,  i have a clearer idea in my head as to how to include these stubs as a proper PEP 561-compliant package if we did.  (and I agree it's a good idea anyway, would keep the `_pymmcore` and `pymmcore` modules closer in `site-packages`).

I can open a PR anytime, but it will probably be easier to incorporate once you've already update the github bundling action.

**Comment by marktsuchida** [comment]
@tlambert03 Done (#44).
