### ISSUE TITLE
'CMMCore' object has no attribute 'getXYStagePosition'

### ISSUE THREAD

**Issue by tlambert03** [micro-manager/pymmcore#65]
just a note so I don't forget:

the [type stubs](https://github.com/micro-manager/pymmcore/blob/5fb6ad14a57d2b10b57d04bc7706ff56f1162c9c/pymmcore/__init__.pyi#L572-L576) indicate that CMMCore has a method `getXYStagePosition` (as in [core](https://javadoc.scijava.org/Micro-Manager-Core/mmcorej/CMMCore.html#getXYPosition-double:A-double:A-)) ... but it doesn't appear to be in the swig object.  Need to dig

**Comment by marktsuchida** [comment]
That function exists in [MMCoreJ](https://github.com/micro-manager/mmCoreAndDevices/blob/d71312341d3580fe2d48f39fee1305ad7ab66dc6/MMCoreJ_wrap/MMCoreJ.i#L872-L877), so it probably crept in when semi-auto-generating the type stubs.

MMCore (C++) itself only has `getXYPosition()`, the latter using out-params.

We should add an equivalent `getXYStagePosition()` to pymmcore. It might be good to check which other functions are similarly needed.
