### ISSUE TITLE
Failing control of MCL_MicroDrive device

### ISSUE THREAD

**Issue by jacopoabramo** [micro-manager/pymmcore#66]
Greetings,

I'm trying to use pymmcore with a Mad City Labs XY stage driver. Whenever I try to set the position (i.e. at [0, 0]) I get `RuntimeError: Error in device "MicroDrive": MCL Error: Handle not valid (-8)`.

In the past I was already able to control the drivers via python by using the `ctypes` package to wrap the DLL, so I'm not quite sure what's the problem.

A small snippet of example code to reproduce the problem:

```python
import pymmcore

mm_dir = "C:/Program Files/Micro-Manager-2.0"

mmc = pymmcore.CMMCore()
print(mmc.getAPIVersionInfo())
mmc.setDeviceAdapterSearchPaths([mm_dir])
mmc.loadDevice(
    "MicroDrive",
    "MCL_MicroDrive",
    "MicroDrive XY Stage"
)

mmc.setXYPosition("MicroDrive", 0, 0)
```

This happens regardless of which position I try to set.

---
EDIT: adding my setup information

OS: Windows 10 (x64)
Python: 3.9.7
MCL DLL version: 2.0
pymmcore version: 10.1.1.70.5

Let me know if you need any other information.

**Comment by marktsuchida** [comment]
I don't know if this is the cause, but you need to initialize devices after loading and before using them.
To do it manually (without a `.cfg` file), you can use `mmc.initializeAllDevices()` or `mmc.initializeDevice("MicroDrive")`.

**Comment by jacopoabramo** [comment]
That did it, thanks.
