### ISSUE TITLE
Error loading device adapter with pymmcore but not micromanager

### ISSUE THREAD

**Issue by inchinn1** [micro-manager/pymmcore#72]
Hi,
I have an Andor Zyla and it works with Micromanger 2, however when I try to use it via pymmcore I get the following errors when running the quick example from the readme: 

![image](https://user-images.githubusercontent.com/21177232/199257367-ef9da53c-f14d-4312-95dc-37689b8a9216.png)

I figured this error just might be due to the inserted backslash that happens in mmc.loadSystemConfiguration(os.path.join(mm_dir, "MMConfig_demo.cfg")). So I tried to change directory to the config file and then load it, which gives the following error:

![image](https://user-images.githubusercontent.com/21177232/199258807-c27e2b5c-9852-4f35-83e1-6ff8fec69907.png)

Strangely the camera works fine with micromanager, so the issue must be either with pymmcore or some aspect of the mmgr_dal_AndorSDK3.dll that only pymmcore uses. The micromanager folder has been added to PATH.

Any help or fixes for this would be greatly appreciated.

**Comment by marktsuchida** [comment]
From the last error message I can see that you are running pymmcore 10.3.0.71.0 (the latest), which requires device interface version 71, together with an older Micro-Manager that has device interface version 70. You can either downgrade to pymmcore 10.1.1.70.6, or upgrade your Micro-Manager to the 2022-10-31 nightly build (which is the first that has 71).

This is also a [known problem](https://github.com/micro-manager/mmCoreAndDevices/issues/288) with the Micro-Manager nightly builds between 2022-10-25 and 2022-10-30, so best to avoid those when using pymmcore.

Hope this helps; please reopen if not.

**Comment by kasliwalr** [comment]
Getting similar error with Demo camera. I created a ticket for it under `mmCoreAndDevices` repo, adding that for reference here - https://github.com/micro-manager/mmCoreAndDevices/issues/311
